### ISSUE TITLE
How to use as a library author?

### ISSUE THREAD

**Issue by cjbottaro** [arnomi/elixir-flex-logger#1]
Hello! I just discovered this package and it seems to do something I've been wanting in Elixir for a long time.

As a library author, do I need to do anything _in my library_ for people to use this? Do I have to to set `:application` metadata when logging from within my library?

Or can I just call vanilla `Logger.debug` from my library and the end user can still disable debug logging for my lib?

Thanks for this and the help!

**Comment by arnomi** [comment]
You don’t need to do anything special within your library as FlexLogger works on top of Elixir‘s standard log system.
